---
event:
  provider: kafka
  brokers: "127.0.0.1:9092"
entity:
  type: "User"
  store-address: "http://127.0.0.1:3000"
index:
  provider: elasticsearch
  hosts:
    - "http://localhost:9200"
  retryPolicy:
    maxRetries: 5
    retryInterval: 5000
  fields:
    -  name: "id"
    -  name: "displayName"
    -  name: "organization.id"
    -  name: "organization.displayName"
    -  name: "organization.group.id"
    -  name: "organization.group.displayName"



