---
event:
  provider: kafka
  brokers: "kafka:9092"
entity:
  store-address: "http://entity-store:3000"
index:
  provider: elasticsearch
  hosts:
    - "http://es01:9200"
  retryPolicy:
    maxRetries: 5
    retryInterval: 5000
  entities:
    User:
      indexBatchSize: 5
      fields:
        - name: "id"
        - name: "displayName"
        - name: "organization.id"
        - name: "organization.displayName"
        - name: "organization.group.id"
        - name: "organization.group.displayName"
    Organization:
      indexBatchSize: 3
      fields:
        - name: "id"
        - name: "displayName"
        - name: "group.id"
        - name: "group.displayName"



