type Query {
  user(id: String): User
  organization(id: String): Organization
  group(id: String): Group
}
type User {
  id: String
  displayName: String
  titles: [String]
  organization: [Organization]
  supervisor: User
  User_by_supervisorId: [User]
}
type Organization {
  id: String
  displayName: String
  group: Group
  User_by_organizationIds: [User]
}
type Group {
  id: String
  displayName: String
  Organization_by_groupId: [Organization]
}