version: 2
jobs:
  test:
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - run:
          command: yarn install
      - run:
          command: yarn build
      - run:
          command: yarn lint
      - run:
          command: yarn test
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
